#!/bin/bash -e

SLEEP_TIME=1

case "${1-}" in 
    pull)
        image_file=$2
        image="${3-}"
        if [ -z $3 ]; then
            echo "Please specify an image"
            exit 1
        fi
        echo "== Pull image $image"
        sleep $SLEEP_TIME
        touch $(pwd)/$image_file
        echo "== DONE"
        exit 0
        ;;
    *)
        echo "usage 'singularity pull <image>'"
        exit 1
esac

